CREATE TABLE IF NOT EXISTS label_templates (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(80) NOT NULL,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(50) NOT NULL,
    tags VARCHAR(255) NULL,
    description VARCHAR(500) NULL,
    tone VARCHAR(16) NOT NULL DEFAULT '#7B2840',
    paper_no VARCHAR(40) NULL,
    paper_w_mm DECIMAL(8,2) NOT NULL DEFAULT 70.00,
    paper_h_mm DECIMAL(8,2) NOT NULL DEFAULT 36.00,
    paper_shape VARCHAR(20) NOT NULL DEFAULT 'rect',
    document_json LONGTEXT NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    UNIQUE KEY uk_label_templates_slug (slug),
    KEY idx_label_templates_cat (category, is_active, sort_order),
    KEY idx_label_templates_active (is_active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
